# Generated by Django 3.0.3 on 2020-02-28 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25)),
                ('category_image', models.ImageField(upload_to='lib/static/Categories_images')),
            ],
            options={
                'ordering': ['-category'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('cover', models.ImageField(upload_to='lib/static/Books_covers')),
                ('location', models.CharField(max_length=250)),
                ('publish_date', models.DateField()),
                ('Edition', models.CharField(max_length=10)),
                ('about', models.CharField(max_length=500)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib.Category')),
            ],
        ),
    ]
