# Generated by Django 3.0.3 on 2020-02-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='1', max_length=100),
        ),
    ]
