# Generated by Django 3.0.3 on 2020-02-29 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0002_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
