# Generated by Django 3.0.3 on 2020-02-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0003_auto_20200229_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='1', max_length=250),
        ),
    ]
