# Generated by Django 3.0.3 on 2020-02-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0004_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
