# Generated by Django 3.0.3 on 2020-03-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib', '0006_auto_20200229_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='about',
        ),
        migrations.AddField(
            model_name='book',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='No description found', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
